/* Generated by Yosys 0.5 (git sha1 c3c9fbf, gcc 4.8.2-19ubuntu1 -O2 -fstack-protector -fPIC -Os) */

module buf_test(a, b, c);
  input a;
  input b;
  output c;

  NAND2X1 _0_ (
	.A(a),
	.B(b),
	.Y(c)
   );
endmodule
